<?php
/**
 * Copyright © 2016 Mozg. All rights reserved.
 * See LICENSE.txt for license details.
 */

/* @var $this Mozg_Productpageshipping_Block_Estimate_Form */
?>

<!-- MOZG -->
<?php if ($this->isEnabled()): ?>

<?php
$ui_colors = array('black','blue','orange','green','red','purple','teal');
$ui_color = $ui_colors[array_rand($ui_colors)];
?>

<div id="block-shipping-form" class="block block-shipping-estimate  ui <?php echo $ui_color ?> segment">
    <div class="block-title">
        <strong><span><?php echo $this->__('Estimate Shipping') ?></span></strong>
    </div>
    <div class="block-content">
    <p class="block-subtitle"><?php echo $this->__('Enter your destination to get a shipping estimate.') ?></p>
    <ul class="shipping-estimation-form" id="shipping-estimation-form">
        <?php if ($this->isFieldVisible('country')): ?>
            <li class="item" id="li-estimate-country">
                <label for="estimate_country"<?php /* ?> class="required"<?php */ ?>><?php /* ?><em>*</em><?php */ ?><?php echo $this->__('Country') ?></label>
                <div class="input-box">
                    <?php echo Mage::getBlockSingleton('directory/data')->getCountryHtmlSelect(
                            ($this->getFieldValue('country') ? $this->getFieldValue('country') : $this->getConfig()->getDefaultCountry()),
                            'estimate[country_id]',
                            'estimate_country'
                        );
                    ?>
                </div>
            </li>
        <?php else: ?>
            <input type="hidden" id="estimate_country" name="estimate[country_id]" value="<?php echo $this->htmlEscape($this->getConfig()->getDefaultCountry())?>" />
        <?php endif; ?>
        <?php if ($this->isFieldVisible('region')): ?>
            <li class="item" id="li-estimate-region">
                <label for="estimate_region_id"<?php if ($this->isFieldRequired('region')):?> class="required" <?php endif;?>><?php if ($this->isFieldRequired('region')):?><em>*</em><?php endif;?><?php echo $this->__('State/Province') ?></label>
                <div class="input-box">
                    <select id="estimate_region_id" name="estimate[region_id]" title="<?php echo __('State/Province') ?>" style="display:none;"<?php echo ($this->isFieldRequired('region') ? ' class="validate-select"' : '') ?>>
                        <option value=""><?php echo  $this->__('Please select an option') ?></option>
                    </select>
                   <script type="text/javascript">
                   //<![CDATA[
                       $('estimate_region_id').setAttribute('defaultValue',  '<?php echo $this->jsQuoteEscape($this->getFieldValue('region_id')); ?>');
                   //]]>
                   </script>
                   <input type="text" id="estimate_region" name="estimate[region]" value="<?php echo $this->htmlEscape($this->getFieldValue('region')) ?>"  title="<?php echo $this->__('State/Province') ?>" class="input-text" style="display:none;" />
               </div>
            </li>
            <script type="text/javascript">
            //<![CDATA[
                new RegionUpdater('estimate_country', 'estimate_region', 'estimate_region_id', <?php echo $this->helper('directory')->getRegionJson() ?>);
            //]]>
            </script>
        <?php endif; ?>
        <?php if($this->isFieldVisible('city')): ?>
            <li class="item" id="li-estimate-city">
                <label for="city"<?php /*if ($this->isFieldRequired('city')):?> class="required" <?php endif;*/?>><?php /*if ($this->isFieldRequired('city')):?><em>*</em><?php endif;*/?><?php echo $this->__('City') ?></label>
                <div class="input-box">
                    <input class="input-text<?php /*if ($this->isFieldRequired('city')):?> required-entry<?php endif;*/?>" id="estimate_city" type="text" name="estimate[city]" value="<?php echo $this->htmlEscape($this->getFieldValue('city')) ?>" />
                </div>
            </li>
        <?php endif; ?>
        <?php if ($this->isFieldVisible('postcode')): ?>
            <li class="item" id="li-estimate-postcode">
                <label for="estimate_postcode"<?php if ($this->isFieldRequired('postcode')):?> class="required" <?php endif;?>><?php if ($this->isFieldRequired('postcode')):?><em>*</em><?php endif;?><?php echo $this->__('Zip/Postal Code') ?></label>
                <div class="input-box">
                    <input class="input-text validate-postcode<?php /*if ($this->isFieldRequired('postcode')):?> required-entry<?php endif;*/?>" type="text" id="estimate_postcode" name="estimate[postcode]" value="<?php echo $this->htmlEscape($this->getFieldValue('postcode')) ?>" />
                </div>
            </li>
       <?php endif; ?>
       <?php /*if ($this->isFieldVisible('coupon_code')): ?>
            <li class="item">
                <label for="estimate_coupon_code"<?php if ($this->isFieldRequired('coupon_code')):?> class="required" <?php endif;?>><?php if ($this->isFieldRequired('coupon_code')):?><em>*</em><?php endif;?><?php echo $this->__('Coupon Code') ?></label>
                <div class="input-box">
                    <input class="input-text <?php if ($this->isFieldRequired('coupon_code')):?> required-entry<?php endif;?>" type="text" id="estimate_coupon_code" name="estimate[coupon_code]" value="<?php echo $this->htmlEscape($this->getFieldValue('coupon_code')) ?>" />
                </div>
            </li>
       <?php endif; ?>
       <?php if ($this->isFieldVisible('cart')): ?>
            <li class="item radio">
                <label for="estimate_cart_yes"><?php echo $this->__('Include Cart Items') ?></label>
                <div class="input-box">
                    <input type="radio" id="estimate_cart_yes" name="estimate[cart]" value="1" <?php if ($this->useShoppingCart()): ?> checked="checked"<?php endif;?> /><?php echo $this->__('Yes') ?>
                    <input type="radio" id="estimate_cart_no" name="estimate[cart]" value="0" <?php if (!$this->useShoppingCart()): ?> checked="checked"<?php endif;?> /> <?php echo $this->__('No') ?>
                </div>
            </li>
       <?php elseif ($this->useShoppingCart()):?>
            <input id="estimate_cart_yes" type="hidden" name="estimate[cart]" value="1" />
       <?php endif;*/ ?>
    </ul>
    <script type="text/javascript">decorateList('shipping-estimation-form');</script>
    <div class="actions">
        <span class="please-wait f-left" id="shipping-estimate-loading-message" style="display:none;">
            <?php echo $this->__('Loading rates...') ?>
        </span>
        <div class="f-right">
            <button type="button" title="<?php echo $this->__('Get a Quote') ?>" onclick="estimateProductShipping('shipping-estimate-results')" class="button"><span><span><?php echo $this->__('Get a Quote') ?></span></span></button>
        </div>
    </div>
    </div>
</div>

<div id="shipping-estimate-results" style="display:none"></div>

<?php

$_product = Mage::registry('product');
$product_id = $_product->getId();

?>

<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.maskedinput/1.4.1/jquery.maskedinput.js" type="text/javascript"></script>

<script type="text/javascript">
//<![CDATA[

//---

function zip_Event(event) {

    console.log(arguments.callee.name);

    var element = event.element();
    $('estimate_postcode').removeClassName("validate-zip-international");
    $('estimate_postcode').addClassName("validate-zip-brasil");
}

$('estimate_postcode').observe('focus', zip_Event);

jQuery('input[name*="estimate[postcode]"]').mask('99999-999');

//---

//]]>
</script>

<script type="text/javascript">
//<![CDATA[

//---

var url = '//js.maxmind.com/js/apis/geoip2/v2.1/geoip2.js';
var callback = function() {

    console.log('callback');
    console.log(arguments.callee.name);

    //console.dir(geoip2);

    var onSuccess = function(location){
        response = JSON.stringify(location, undefined, 4);
        //console.log(response);

        //console.log(location.subdivisions);

        city = location.city.names.en;
        uf = location.subdivisions[0].iso_code;

        
        setTimeout(function() {
            selectbox = $('estimate_region_id');
            value = uf;
            //console.log(value);
            if(selectbox){
                var option = selectEstado(selectbox, value);
            }
            //console.log(option);
        }, 1000);
        

        if($('estimate_city')){
            $('estimate_city').value = city;
        }        

    };

    var onError = function(error){
        response = JSON.stringify(error, undefined, 4);
        console.log(response);
    };

    geoip2.city(onSuccess, onError);


};
var type = 'js';
loadJsCssfile(url, callback, type);

//---

function estimateProductShipping(elementReturn)
{

    console.log(arguments.callee.name);
    console.log(arguments);

    postcode = $('estimate_postcode').value;

    console.log(postcode);

    if(!postcode){
        $('estimate_postcode').focus();
        return false;
    }

    var estimationUrl = '<?php echo $this->jsQuoteEscape($this->getEstimateUrl());?>'+'id/'+childProductId+'/';

    var items = $$(['.shipping-estimation-form input',
                    '.shipping-estimation-form select',
                    '#product_addtocart_form input',
                    '#product_addtocart_form select']);

    var validationResult = true;

    // Check the valid input
    if (!items.map(Validation.validate).all()) {
        return;
    }

    var parameters = Form.serializeElements(items, true);

    console.log(items);
    console.log(Form);
    console.log(parameters);

    //$('shipping-estimate-loading-message').show();
    //$('shipping-estimate-results').hide();
    pre.show('Processando...');

    new Ajax.Updater(elementReturn, estimationUrl, {
        parameters: parameters,
        onComplete: function() {
            //$('shipping-estimate-loading-message').hide();
            $(elementReturn).show();

            console.log('pre');

            console.log(pre);

            pre.hide();            

        }
    });

}

//---

//]]>
</script>
<?php endif;?>
<!-- / MOZG -->